(include "timing.scm")
(define-library (sicp ch1)
  (export square)
  (import (except (scheme base) square)
          (scheme char)
          (scheme complex)
          (scheme inexact)
          (scheme file))
  (begin
    (define (square n)
      (* n n))))

(define-library (sicp ch1 tests)
  (export ex13test)
  (import (scheme base)
          (prefix (sicp ch1) sicp-)
          (srfi 64))
  (begin
    (define (ex13test)
      (test-begin "test")
      (test-end "test"))))

(import (sicp ch1)
        (sicp timing)
        (sicp ch1 tests))
