(define-library (sicp timing)
  (export time-length)
  (import (scheme base)
          (scheme time)) 
   (begin 
     (define (time-length functionToTime)
       (let ((start (current-jiffy)))
         (functionToTime)
         (inexact (/ (- (current-jiffy) start)
                     (jiffies-per-second)))))))

(define-library (sicp ch1)
  (export )
  (import (scheme base)
          (scheme char)
          (scheme complex)
          (scheme inexact)
          (scheme file))
  (begin))))))))

(import (sicp ch1)
        (sicp timing))
